export const FETCH_TASKS = "FETCH_TASKS";
export const NEW_TASK = "NEW_TASK";
export const DELETE_TASK = "DELETE_TASK";

export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const RECOVER_USER = "RECOVER_USER";

export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";

export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_RESPONSE = "AUTH_LOGIN_RESPONSE";

export const AUTH_SIGNUP_REQUEST = "AUTH_SIGNUP_REQUEST";
export const AUTH_SIGNUP_RESPONSE = "AUTH_SIGNUP_RESPONSE";

export const AUTH_FAIL = "AUTH_FAIL";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const AUTH_STATE_CHANGED = "AUTH_STATE_CHANGED";
